DDD-Community/DDD-11-Sonny-Polabo-FE

- .eslintrc.json
- .gitignore
- .storybook/main.ts
- .storybook/preview.ts
- package-lock.json
- package.json
- src/app/page.tsx
- src/components/Button/Button.stories.tsx
- src/components/Button/index.tsx
- tailwind.config.ts
https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/issues/6
- 공통 버튼 컴포넌트 작업했습니다.
- 스토리북 설정했습니다.
- 버튼 컴포넌트에 추가적인 작업이 필요할 것 같은 부분이나 질문 있으시면 코멘트 남겨주세요!
- 스토리북은 개발시 UI 참고용으로만 사용하려고 설정해두었습니다. 굳이 컴포넌트마다 스토리북 생성하거나 할 필요는 없고 필요한 경우만 알아서 사용하면 좋을 것 같아요!
- 구체적인 버튼 스타일은 디자인나오면 수정하겠습니다. 우선은 임시적인 스타일이라고 봐주세요.
> [Feature/6] 공통 버튼 컴포넌트 작업

- src/lib/api/base.ts
- src/lib/api/board.ts
- src/lib/api/file.ts
- src/lib/api/index.ts
- src/lib/api/polaroid.ts
- src/types/board.ts
- src/types/file.ts
- src/types/index.ts
- src/types/polaroid.ts
- Swagger에 명시된 api 형식과 통일하도록 작업 진행했습니다.
- API 타입, url 등 수정
.env.local 파일에 API_HOST 설정이 필요합니다.
> [FEATURE] API 형식 수정

- .gitignore
- src/app/layout.tsx
- src/components/Button/Button.stories.tsx
- src/components/Button/index.tsx
- src/components/TagButton/TagButton.stories.tsx
- src/components/TagButton/index.tsx
- tailwind.config.ts
- 디자인 시스템 적용
- 폰트 스타일 디자인 시스템 적용했습니다.
- 해솜체 추가했습니다.
- 버튼 컴포넌트 디자인 적용했습니다.
- TagButton 생성했습니다.
- font 관련 theme은 figma local variable 기준으로 작업했습니다.
> [Feature/6] 디자인 시스템 적용

- .github/workflows/cicd.yml
- src/components/Polaroid/PolaroidMaker.tsx
- https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/issues/38
- 배포시 .env 파일에 API HOST 설정하는 부분 추가했습니다.
- MAX_LENGTH는 페이지에서 정의하는게 맞는 거 같아서 삭제했었는데 사용되는 부분이 있어서 빌드시 에러가 발생하더라구요. 그래서 페이지에서 다시 정의하였습니다.
> [Feature/38] 배포시 API HOST 설정 

- .github/workflows/cicd.yml
- src/app/(board)/board/create/components/BoardAvailabilityCheckModal.tsx
- src/app/(board)/board/create/page.tsx
- src/app/(home)/components/CopyLinkBtn.tsx
- src/components/Modal/index.tsx
- src/lib/api/board.ts
- https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/issues/44
- 보드 생성 제한 API 추가
- 보드 생성 제한 모달 추가
- Modal 수정
- Modal 컴포넌트에 대해서 크게 3가지를 수정했습니다.
1. Modal에 closeOnOutsideClick prop을 추가했습니다. 해당 prop이 false인 경우 모달 외부 클릭시에도 모달이 닫히지 않습니다. default는 true라서 기존 모달에 영향은 없습니다.
2. Modal onConfirm이 모달이 닫힌 후 실행되도록 수정했습니다. 
3. Modal이 열릴때 가끔 트랜지션이 스킵되는 현상이 있어서 requestAnimationFrame을 이용해 다음 렌더링 주기 직전에 isVisible 값을 변경하여 트랜지션이 정상적으로 실행되도록 수정했습니다.
> [Feature/44] 보드 생성 제한 Modal 추가 및 Modal 컴포넌트 수정

- src/app/(board)/board/[boardId]/components/modals/AskBfCloseModal.tsx
- src/components/Modal/index.tsx
https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/issues/54
모달 애니메이션 제거
예/아니오 버튼 순서 변경
플라로이드 등록 취소 모달 텍스트 수정
- 폴라로이드 등록 취소 모달 수정된 부분 확인 부탁드려요!
- 모달 애니메이션 제거하였습니다.
- 모달 confirm 버튼 클릭시 닫기 후 confirm이 실행됩니다.
> [Feature/54] QA 모달 수정

- package-lock.json
- package.json
- src/app/(board)/board/[boardId]/actions/uploadAction.ts
- src/app/(board)/board/[boardId]/components/CreatePolaroidModal/index.tsx
- src/components/Polaroid/PolaroidMaker.tsx
- src/lib/api/file.ts
#57 
카카오톡 안드로이드에서 이미지 업로드되지 않는 문제가 용량 문제인 것 같아서 업로드 전 압축했습니다. 
수정할 부분 있으면 알려주세요!
> [Feature/57] image compression

- src/app/(board)/board/create/components/BoardNameForm.tsx
- src/app/(board)/board/create/components/BoardNameRecommendations.tsx
- src/app/(home)/page.tsx
- src/app/layout.tsx
- src/components/Modal/index.tsx
- src/components/TextInput/index.tsx
- 보드 페이지 텍스트 크기 수정
- TextInput 넓이 수정
> [Feature/QA] 2차 QA

- .github/workflows/cicd.yml
- src/app/(board)/board/[boardId]/page.tsx
- src/app/layout.tsx
- src/app/sitemap.ts
- sitemap.ts 추가
- title, description 추가
- 보드 페이지 동적 metadata 추가
- workflow에 GA_ID 환경변수 추가
> [Feature/Metadata] Metadata 설정

- .github/workflows/cicd.yml
- src/components/GoogleAnalytics.tsx
- src/lib/utils/env.ts
- 개발 서버 구축 작업 진행했습니다.
- 개발 서버 구축
- WF 수정
- develop push 되는 경우 dev.polabo.site로 배포됩니다.
- release 태그 생성시 polabo.site로 배포됩니다.
- GA는 개발 환경에서는 설정하지 않도록 수정했습니다.
> [FEATURE/DEV-CICD] 개발 환경 구축

- src/app/mypage/boards/page.tsx
- src/app/mypage/leave/page.tsx
- src/app/mypage/profileEdit/page.tsx
- src/components/Header/HeaderBackButton.tsx
- src/components/Header/index.tsx
- tailwind.config.ts
- https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/issues/67
- 헤더 컴포넌트 추가했습니다.
- 프로필 수정, 탈퇴하기, 보드 페이지 추가했습니다.
- 헤더 컴포넌트 더 나은 방안 있으면 공유 부탁드립니다 ㅎ
| 기능 | 스크린샷 |
| :--: | :------: |
|   헤더 컴포넌트   |    <img width="406" alt="스크린샷 2024-08-05 오후 11 25 15" src="https://github.com/user-attachments/assets/079dc3d0-39cb-4cbf-b77c-dff2335ed3e0">      |
> [FEATURE/67] 헤더 컴포넌트 추가

- next.config.mjs
- src/components/Modal/index.tsx
- src/components/Polaroid/Base/PolaroidImage.tsx
- src/components/Polaroid/PolaroidDetail/index.tsx
- src/components/Polaroid/PolaroidMaker/index.tsx
- src/lib/constants/polaroidConfig.ts
[feat: 모달 Overlay touch none 추가](https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/commit/68ce1034b3dcf99ffbc4f65496047a5e37b05a73)
[feat: 모달 Overlay touch pinch zoom으로 변경](https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/commit/030dd46f67553296d0cf16ca7cfaae731414ef6f)
[feat: 폴라로이드 Next Image 사용하도록 수정](https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/commit/e4e570e355ea2c26e95a6f1ad5b0152c0d4eb7a5)
> [QA] 3차 QA

- src/app/board/[boardId]/_components/CreatePolaroidModal/CreatePolaroid.tsx
- src/app/board/[boardId]/_components/CreatePolaroidModal/ThemaSelect.tsx
- src/app/board/create/_components/BoardNameForm.tsx
- src/app/board/create/_components/BoardNameRecommendations.tsx
- src/app/board/create/page.tsx
- src/app/layout.tsx
- src/components/Polaroid/PolaroidMaker/PolaroidNicknameInput.tsx
[feat: 보드 추천 애니메이션 적용 수정](https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/commit/2357eb3e8ee428cffc9e93715c786961ca236320)
[feat: 보드 추천 클릭 제거](https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/commit/f14695932e66db6f596c2af925e50967360aba59)
[feat: 폴라로이드 생성 업로드 버튼 수정](https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/commit/5e2ebb3b8d2d88b5e67ed25f75b74b918cc7cb24)
[feat: 폴라로이드 생성 오버스크롤 수정](https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/commit/dc40de6d653f9aaec6809ffddbf9934ea25f401d)
[feat: 폴라로이드 닉네입 입력 넓이 계산 로직 수정](https://github.com/DDD-Community/DDD-11-Sonny-Polabo-FE/commit/e0a9ea9439627b4a550007d25ca205234fd8bc33)
- 개선할 부분있으면 알려주세요!
> [FIX] 4차 QA

- src/app/board/[boardId]/_hooks/useSnsShare.ts
> [FIX/127] 4-2차 QA

- src/app/board/create/theme/_components/ThemaSelect.tsx
#137 
- 보드 생성 테마 선택 페이지 scrollbar hide 적용했습니다
> [QA/137] 5차 QA

- src/app/(home)/_components/TotalCount.tsx
- src/app/(onboarding)/signup/_components/steps/NicknameForm.tsx
- '지금까지' 뒤에 띄어쓰기가 빠져있어서 추가했습니다.
- 닉네임 입력이 중앙 정렬이 안되어 있어서 추가했습니다. 
| 기능 | 스크린샷 |
| :--: | :------: |
|  홈    |    <img width="408" alt="스크린샷 2024-12-18 오후 10 58 11" src="https://github.com/user-attachments/assets/9948a3cf-212b-4bba-b472-8878f34b02fc" />      |
|  닉네임 |   <img width="408" alt="스크린샷 2024-12-18 오후 10 58 23" src="https://github.com/user-attachments/assets/6859f5f6-8ba7-4753-bb2f-8bb40f73753a" />   |
> [FEATURE] 스타일 수정

- src/components/Polaroid/PolaroidDetail/index.tsx
- 상세 모달에서 스와이프, 삭제 안되는 문제 고쳤습니다
> [FIX] 폴라로이드 상세 모달 

- package-lock.json
- package.json
- src/app/(home)/page.tsx
- src/app/board/[boardId]/_components/PolaroidList/PolaroidListItem.tsx
- src/app/layout.tsx
- src/components/Polaroid/Base/PolaroidImage.tsx
- src/components/Tutorial/Tutorial.tsx
- tailwind.config.ts
<details>
<summary>튜토리얼 dynamic resizing</summary>
- 튜토리얼 타깃 렌더링 시 위치와 크기가 변경되면 타깃을 제대로 추적하지 못하는 문제를 발견       
- ResizeObserver를 활용하여 해결      
| before | after |
| :--: | :------: |
|  ![image](https://github.com/user-attachments/assets/0d788824-f926-4fde-acb9-f80dac6cca74)  |  ![image](https://github.com/user-attachments/assets/21fb17c9-484c-46c0-ae57-68b3969c5296) |
</details>
<details>
<summary>이미지 최적화 (sharp 추가)</summary>
- **Lighthouse Performance 점수**: 66 → 75 (Home 화면)
- **Largest Contentful Paint (LCP)**: sharp를 추가하여 이미지 크기와 포맷을 최적화해 개선
| Before | After |
| :--: | :------: |
| ![Before Image](https://github.com/user-attachments/assets/45970840-5c55-4486-8ff2-724f3a8c82e1) |<img width="400" alt="After Image" src="https://github.com/user-attachments/assets/c9a10547-453c-4690-86eb-3d5 …
> [Feature] 튜토리얼 타깃 리사이징, 성능 최적화 

- .github/workflows/cicd.yml
- src/app/board/[boardId]/decorate/_components/DecorateScreenshot.tsx
- src/app/board/api/screenshot/route.ts
- 스크린샷 속도가 너무 느려서 성능을 개선했습니다.
- 공유 메모리 크기 증가
- 불필요한 useEffect 의존성 제거 (스크린샷 빈도 줄임)
- puppeteer browser 싱글 인스턴스 사용
- puppeteer 성능 관련 옵션 추가
> [FEATURE] 스크린샷 성능 개선

- src/app/board/[boardId]/_components/Header/SelectModeHeader.tsx
- src/app/board/[boardId]/_contexts/SelectModeContext.tsx
- src/app/board/[boardId]/decorate/_components/DecorateScreenshot.tsx
- src/app/board/[boardId]/decorate/_components/SelectStickerModal/index.tsx
- src/components/Toast/index.tsx
- src/lib/utils/image.ts
- 6.5차 QA 수정 진행했습니다.
- https://www.notion.so/hwanheejung/6-QA-11a4a6963d4f4efbb6e8b8a029af6c28?pvs=4
- 보드 이미지 다운로드시 토스트
- 폴라로이드 선택 페이지 뒤로가기 버튼
- 보드 꾸미기 비회원인경우 최근 사용 스티커 탭 비노출
| 기능 | 스크린샷 |
| :--: | :------: |
|  보드 이미지 다운로드시 토스트    |    ![스크린샷 2025-01-11 오전 12 25 35](https://github.com/user-attachments/assets/3254e350-23af-4956-be3c-44da5025daa6)|
|  폴라로이드 선택 페이지 뒤로가기    |    ![스크린샷 2025-01-11 오전 12 26 34](https://github.com/user-attachments/assets/f17549c9-553c-423c-babe-57fbad866098) |
|  보드 꾸미기 비회원인경우 최근 사용 스티커 탭 비노출    |    ![스크린샷 2025-01-11 오전 12 25 50](https://github.com/user-attachments/assets/8602f284-f425-4dea-9f82-a74ca3dd98f9) |
> [FEATURE] 6.5차 QA
